CREATE DATABASE web;
SHOW DATABASES;

CREATE USER 'user'@'%' IDENTIFIED BY '1234';
CREATE USER 'user'@'localhost' IDENTIFIED BY '1234';
FLUSH PRIVILEGES;

GRANT ALL PRIVILEGES ON web.* TO 'user'@'%';
GRANT ALL PRIVILEGES ON web.* TO 'user'@'localhost';